version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:  
      - ./static:/usr/src/app/static

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: postgres
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:  
      - ~/Database/Postgres:/var/lib/postgresql/data